#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if ! test $GITHUB_ACTIONS && ! test $SKIP; then
  pnpm i
  for ws in $(git diff --name-only --cached | grep -oP '^(aeria-([^/\.]+)|playground)(?=/)' | uniq); do
    pnpm --filter="./${ws}" lint:fix
  done
fi

git add pnpm-lock.yaml

